### ISSUE TITLE
No component found for view with name ARTSurfaceView

### ISSUE THREAD

**Issue by ggaabe** [tomauty/react-native-chart#80]
Hi, just tried the beta out. Thanks for pushing.

When I try to create a pie chart, like so:

`<Chart style={styles.chart} chartData={this.state.pieChart} xLabels={this.state.xLabels} type="pie" />`

React-native throws the error:
`No component found for view with name ARTSurfaceView`

**Comment by tomauty** [comment]
Ah right, I need to add that to the instructions. You have to link the ART library on iOS.

**Comment by tomauty** [comment]
`rnpm link` should solve it for you. Let me know :)

**Comment by ggaabe** [comment]
It linked the libraries but it's still throwing the error, after restarting the terminal as well :-/
**Edit: It only linked the RNChart library. How do I go about linking the art library as well?**

**Comment by tomauty** [comment]
Adding some instruction screenshots to README. Try this:

<img width="366" alt="screen shot 2016-06-17 at 3 39 24 pm" src="https://cloud.githubusercontent.com/assets/1112872/16162504/e4f284f4-34a1-11e6-9819-49f7b3ee4fd3.png">
<img width="435" alt="screen shot 2016-06-17 at 3 39 42 pm" src="https://cloud.githubusercontent.com/assets/1112872/16162506/e4f3f35c-34a1-11e6-8fa6-82b1d9162028.png">
<img width="660" alt="screen shot 2016-06-17 at 3 40 00 pm" src="https://cloud.githubusercontent.com/assets/1112872/16162508/e4f8a6cc-34a1-11e6-91d9-2a0fcc1179ab.png">

<img width="182" alt="screen shot 2016-06-17 at 3 40 48 pm" src="https://cloud.githubusercontent.com/assets/1112872/16162505/e4f348f8-34a1-11e6-9790-2bd3f9ee4ac4.png">
<img width="250" alt="screen shot 2016-06-17 at 3 40 03 pm" src="https://cloud.githubusercontent.com/assets/1112872/16162507/e4f50238-34a1-11e6-9b4d-3f883c9f27c4.png">

**Comment by ggaabe** [comment]
Whoa, my react-native directory does not have an ART folder. It doesn't even have a Library folder, just a lib.

How did you get that?

**Comment by tomauty** [comment]
Hmm, just so we didn't miss a step, can you double-check that you did as the README instructions (now) say? I'm not sure how Libraries could be missing : o

**Comment by ggaabe** [comment]
No it was there I'm sleep deprived. Give me a sec I'll tell you if it worked

**Comment by ggaabe** [comment]
Success!!!

Okay, so `rnpm link` didn't link the ART library for some reason. Your manual instructions worked though :-D

**Comment by tomauty** [comment]
Not sure if rnpm will detect the ART dependency or not. Might need to take those instructions out.

**Comment by mquirion** [comment]
rnpm link didn't auto-detect the ART dep for me.  Had to then follow your ART linking steps in the comment above.

**Comment by tomauty** [comment]
I've updated the README to reflect that this is essential for projects without ART already linked.

**Comment by SmiffyKMc** [comment]
Hey, I seem to be having this issue with UWP. Is there some sort of link process for windows devices?
